site_name: CommRL
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

nav:
  - 'Introduction': index.md
  - 'Lit Review':
      - 'Literature_Reviews/CommNet.md'
      - 'Literature_Reviews/DIAL_RIAL.md'
      - 'Literature_Reviews/ATOC.md'
      - 'Literature_Reviews/IC3Net.md'
      - 'Literature_Reviews/MADDPG.md'
      - 'Literature_Reviews/VAIN.md'
      - 'Literature_Reviews/MS-MARL-GCM.md'
      - 'Literature_Reviews/DGN.md'
      - 'Literature_Reviews/TarMAC.md'
      - 'Literature_Reviews/MAGNet-SA-GS-MG.md'
      - 'Literature_Reviews/MADDPG-M.md'
      - 'Literature_Reviews/GA-Comm.md'
      - 'Literature_Reviews/Gated-ACML.md'
      - 'Literature_Reviews/LSC.md'
      - 'Literature_Reviews/Diff Discrete.md'
      - 'Literature_Reviews/ETCNet.md'
      - 'Literature_Reviews/Variable-length Coding.md'
      - 'Literature_Reviews/TMC.md'
      - 'Literature_Reviews/HAMMER.md'
      - 'Literature_Reviews/MAGIC.md'
      - 'Literature_Reviews/FlowComm.md'
      - 'Literature_Reviews/GAXNet.md'
      
  - 'Task Carried Out':
      - 'tasks/tasks_carried.md'
  - 'Findings':
      - 'Findings/KL_divergence.md'
      
      
